"""Add default UUID to sage_knowledge id column

Revision ID: 914eca15d0d2
Revises:
Create Date: 2025-04-17 18:46:16.812582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
import uuid


# revision identifiers, used by Alembic.
revision = '914eca15d0d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add UUID extension if it doesn't exist
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')

    # Modify the id column to have a default UUID value
    op.alter_column('sage_knowledge', 'id',
               existing_type=sa.VARCHAR(),
               server_default=sa.text('uuid_generate_v4()'),
               schema='ai')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove the default value from the id column
    op.alter_column('sage_knowledge', 'id',
               existing_type=sa.VARCHAR(),
               server_default=None,
               schema='ai')

    # ### end Alembic commands ###
